### ISSUE TITLE
Reconnect is failing

### ISSUE THREAD

**Issue by diegoloop** [emqtt/CocoaMQTT#232]
We are getting a _client disconnect_ message  immediately after the connection was successfully setup, this happens when the server is down and then comes to active

According to the traces, while the server is down,  one connection channel is keep opened on port 8883.

When the server is restarted and it tries to reconnect (using `mqttclient.connect`), the connection is established and immediately the connection is closed after few milliseconds. This is also happening, when we call the disconnect message after the device notices that the server is down. 

Any ideas? Thank you for the help. 
I'm using CocoaMQTT 1.1.0 and iOS 11 

**Update:**
Issue is reproducible in iOS 12

**Comment by enggjiten** [comment]
Hi,
I am facing same issue on iOS 12.

**Comment by hegdedhruvad** [comment]
CocoaMQTT - I m also facing problem in connecting (iOS 12)

**Comment by Developer-Mohit** [comment]
CocoaMQTT - Connection Problem.
I am also facing problem in connecting only in iOS12 . Its working fine in other iOS version.
If its connected also but when i m publishing then its again giving disconnected.

**Comment by kvdprasad99** [comment]
facing the same problem in connecting only in iOS12(cocoamqtt)

**Comment by HJianBo** [comment]
Hi, guys. sorry for this bug. It may be caused by the original Timer mechanism.

@jmiltner has fixed the timer mechanism in the #246.

Could you check the auto-reconnect mechanism in the 1.2.0 version? I think it has been fixed!

**Comment by keshavx11** [comment]
tested on 1.2.0. Issue persists. And it is reproducible on iOS 11 and 10 also.

**Comment by HJianBo** [comment]
@keshavx11 Can you provide the example code to help me to reproduce it? Thanks!

**Comment by keshavx11** [comment]
` self.mqtt.username = "user"
            self.mqtt.password = "pass"
            self.mqtt.enableSSL = true
            self.mqtt.autoReconnect = true
            self.mqtt.cleanSession = false
            self.mqtt.autoReconnectTimeInterval = 1
            self.mqtt.keepAlive = 60
            self.mqtt.delegate = self
            self.mqtt.connect()`

**Comment by keshavx11** [comment]
``` 
            self.mqtt.username = "user"
            self.mqtt.password = "pass"
            self.mqtt.enableSSL = true
            self.mqtt.autoReconnect = true
            self.mqtt.cleanSession = false
            self.mqtt.autoReconnectTimeInterval = 1
            self.mqtt.keepAlive = 60
            self.mqtt.delegate = self
            self.mqtt.connect()
```

**Comment by keshavx11** [comment]
I reverted back to v1.1.3 and it works fine for me
but It goes in a connect disconnect loops as soon as I update to 1.2.0

**Comment by HJianBo** [comment]
How do you test the re-connect mechanism?

**Comment by keshavx11** [comment]
Please ignore. The issue i have is because of #259 
Not related to this

**Comment by HJianBo** [comment]
Close it. Pls reopen there if someone has reproduced it again.
